package com.filmy.tracking.processor

import com.filmy.tracking.TrackingParam
import com.google.devtools.ksp.containingFile
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.toTypeName

class TrackingCodeGenerator(
    private val function: KSFunctionDeclaration,
    private val trackingData: TrackingParam,
    private val logger: KSPLogger
) {
    private val functionName = function.simpleName.asString()
    private val packageName = function.packageName.asString()
    private val wrapperFunctionName = "Trackable_$functionName"

    fun generate(): FileSpec {
        val fileSpec = FileSpec.builder(packageName, wrapperFunctionName)
            .addFileComment("Auto Generated by KSP TrackingProcessor\n")
            .addFileComment("Do not modify this file")
        val imports = extractImportStatements()
        addImportsToFile(fileSpec, imports)
        fileSpec.addFunction(generateWrapperFunction())
        return fileSpec.build()
    }

    private fun generateWrapperFunction(): FunSpec {
        val funSpec = FunSpec.builder(wrapperFunctionName)
            .addAnnotation(ClassName("androidx.compose.runtime", "Composable"))
            .addModifiers(KModifier.PUBLIC)

        val requiredParams = function.parameters.filter { it.hasDefault.not() }.toList()

        requiredParams.forEach { parameter ->
            val parameterName = parameter.name?.asString() ?: return@forEach
            val parameterType = parameter.type.toTypeName()

            val paramSpec = ParameterSpec.builder(parameterName, parameterType)

            funSpec.addParameter(paramSpec.build())
        }

        function.typeParameters.forEach { typeParameter ->
            val typeParameterName = typeParameter.name.asString()
            funSpec.addTypeVariable(TypeVariableName(typeParameterName))
        }

        funSpec.addCode(generateFunctionBody())

        return funSpec.build()
    }

    private fun generateFunctionBody(): CodeBlock {
        val codeBlock = CodeBlock.builder()

        codeBlock.addStatement(
            "%T(", ClassName("com.android.filmy.ui", "TrackableContent")
        )
        codeBlock.indent()

        codeBlock.addStatement("trackingParam = %T(", ClassName("com.filmy.tracking", "TrackingParam"))
        codeBlock.indent()
        codeBlock.addStatement("id = %S,", trackingData.id)
        codeBlock.addStatement("name = %S,", trackingData.name)
        codeBlock.addStatement("role = %S,", trackingData.role)

        if (trackingData.metadata.isNotEmpty()) {
        codeBlock.addStatement("metadata = mapOf(")
            trackingData.metadata.entries.forEachIndexed { index, (key, value) ->
                if (index > 0) codeBlock.addStatement(", ")
                codeBlock.addStatement("%S to %S", key, value)
            }
            codeBlock.addStatement(")")
        }

        codeBlock.unindent()
        codeBlock.addStatement("),")

        codeBlock.addStatement("content = {")
        codeBlock.indent()

        codeBlock.add("%N(\n", functionName)
        codeBlock.indent()

        function.parameters.forEachIndexed { index, param ->
            val paramName = param.name?.asString() ?: return@forEachIndexed

            if (index > 0){
                codeBlock.add(",\n")
            }
            if (param.hasDefault) {
                // ✅ Parameter has default - pass the default value directly
                val defaultValue = getDefaultValue(param)

                if (defaultValue != null) {
                    codeBlock.add("%N = %L", paramName, defaultValue)
                    logger.info("  → Using default: $paramName = $defaultValue")
                } else {
                    // Fallback: forward the parameter even if we couldn't extract default
                    codeBlock.add("%N = %N", paramName, paramName)
                    logger.warn("  ⚠️ Could not extract default for $paramName, forwarding")
                }
            } else {
                // ✅ Required parameter - forward from wrapper
                codeBlock.add("%N = %N,", paramName, paramName)
                codeBlock.add("\n")
            }
        }
        codeBlock.addStatement(")")

        codeBlock.unindent()
        codeBlock.addStatement("}")  // Close content lambda
        codeBlock.unindent()
        codeBlock.addStatement(")")  // Close TrackableContent

        return codeBlock.build()
    }

    private fun addImportsToFile(fileSpec: FileSpec.Builder, imports: List<String>) {
        imports.forEach { import ->
            fileSpec.addImport(import.substringBeforeLast("."), import.substringAfterLast("."))
        }
    }

    private fun extractImportStatements(): List<String> {
        val sourceFile = function.containingFile?.filePath ?: return emptyList()

        try {
            val sourceCode = java.io.File(sourceFile).readText()
            val importPattern = Regex("""^import\s+([\w.]+)""", RegexOption.MULTILINE)

            val imports = importPattern.findAll(sourceCode)
                .map { it.groupValues[1] }
                .toList()
            return imports
        } catch (e: Exception) {
            logger.error("Failed to extract imports from $sourceFile: ${e.message}", function)
            return emptyList()
        }
    }

    /**
     * Extracts the default value for a parameter with proper parenthesis matching.
     */
    private fun getDefaultValue(parameter: KSValueParameter): String? {
        if (!parameter.hasDefault) return null

        val paramName = parameter.name?.asString() ?: return null
        val sourceFile = parameter.parent?.containingFile?.filePath ?: return null

        logger.warn("🔍 Extracting default for parameter: $paramName")

        try {
            val sourceCode = java.io.File(sourceFile).readText()

            // Find where parameter declaration starts
            val paramPattern = Regex(
                """$paramName\s*:\s*[\w<>.,?\s\[\]()]+\s*=""",
                RegexOption.MULTILINE
            )

            val match = paramPattern.find(sourceCode)
            if (match == null) {
                logger.warn("  ❌ Could not find parameter '$paramName' in source")
                return null
            }

            // Start extracting right after the '=' sign
            val startIndex = match.range.last + 1

            logger.warn("  📍 Found parameter at index ${match.range}")
            logger.warn("  📝 Context: ${sourceCode.substring(match.range.first, minOf(match.range.last + 50, sourceCode.length))}")

            // Extract the default value expression
            val defaultValue = extractBalancedExpression(sourceCode, startIndex)

            if (defaultValue == null) {
                logger.warn("  ❌ Could not extract default value")
                return null
            }

            logger.warn("  ✅ Extracted: '$defaultValue'")

            // Check if it's a function call
            if (defaultValue.contains("(")) {
                logger.warn("  ⚠️ Default is a function call - may need imports!")
            }

            return defaultValue

        } catch (e: Exception) {
            logger.error("  ❌ Exception: ${e.message}", parameter)
            return null
        }
    }

    /**
     * Extracts an expression with balanced parentheses and braces.
     * Stops at comma or closing paren at depth 0.
     */
    private fun extractBalancedExpression(source: String, startIndex: Int): String? {
        if (startIndex >= source.length) return null

        val result = StringBuilder()
        var parenDepth = 0
        var braceDepth = 0
        var bracketDepth = 0
        var i = startIndex
        var inString = false
        var inChar = false

        // Skip leading whitespace
        while (i < source.length && source[i].isWhitespace()) {
            i++
        }

        while (i < source.length) {
            val char = source[i]
            val prevChar = if (i > 0) source[i - 1] else ' '

            // Handle string literals
            if (char == '"' && prevChar != '\\') {
                inString = !inString
                result.append(char)
                i++
                continue
            }

            // Handle char literals
            if (char == '\'' && prevChar != '\\') {
                inChar = !inChar
                result.append(char)
                i++
                continue
            }

            // Inside string or char - just append
            if (inString || inChar) {
                result.append(char)
                i++
                continue
            }

            // Outside strings - check for delimiters
            when (char) {
                '(' -> {
                    parenDepth++
                    result.append(char)
                }
                ')' -> {
                    if (parenDepth == 0) {
                        // Reached end of function signature
                        break
                    }
                    parenDepth--
                    result.append(char)
                }
                '{' -> {
                    braceDepth++
                    result.append(char)
                }
                '}' -> {
                    if (braceDepth == 0) {
                        // Reached end of containing block
                        break
                    }
                    braceDepth--
                    result.append(char)
                }
                '[' -> {
                    bracketDepth++
                    result.append(char)
                }
                ']' -> {
                    bracketDepth--
                    result.append(char)
                }
                ',' -> {
                    if (parenDepth == 0 && braceDepth == 0 && bracketDepth == 0) {
                        // Reached next parameter
                        break
                    }
                    result.append(char)
                }
                else -> {
                    result.append(char)
                }
            }

            i++
        }

        val extracted = result.toString().trim()

        // Remove trailing comments
        return extracted.replace(Regex("""//.*$"""), "").trim()
    }
}